version: '3.8'

services:
    app:
        image: golang-redis-example
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
